name: lug-wiki
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.9.14=h4653dfc_0
  - click=8.1.3=py310hbe9552e_0
  - ghp-import=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hbe9552e_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.39.3=h76d750c_0
  - libzlib=1.2.12=h03a7124_3
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310hf8d0d8f_1
  - mergedeep=1.3.4=pyhd8ed1ab_0
  - mkdocs=1.3.0=pyhd8ed1ab_0
  - mkdocs-material=8.5.1=pyhd8ed1ab_0
  - mkdocs-material-extensions=1.0.3=pyhd8ed1ab_2
  - ncurses=6.3=h07bb92c_1
  - openssl=3.0.5=h03a7124_2
  - packaging=21.3=pyhd8ed1ab_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pymdown-extensions=9.5=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.10.6=hae75cb6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyyaml=6.0=py310hf8d0d8f_4
  - pyyaml-env-tag=0.1=pyhd8ed1ab_0
  - readline=8.1.2=h46ed386_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.12=he1e0b03_0
  - tzdata=2022c=h191b570_0
  - watchdog=2.1.9=py310h02f21da_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zipp=3.8.1=pyhd8ed1ab_0
prefix: /Users/lihaojun/miniforge3/envs/lug-wiki
